name = "youtube_views"
version = "1.0.0"

description = "Fetch statistics of a YouTube playlist's videos"
licences = ["Apache-2.0"]
repository = { type = "github", user = "giacomocavalieri", repo = "youtube_views" }

# For a full reference of all the available options, you can have a look at
# https://gleam.run/writing-gleam/gleam-toml/.
[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
gleam_http = ">= 4.3.0 and < 5.0.0"
gleam_httpc = ">= 5.0.0 and < 6.0.0"
gleam_json = ">= 3.1.0 and < 4.0.0"
envoy = ">= 1.1.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
